apiVersion: v1
kind: Secret
metadata:
  name: spear-credentials
  annotations:
    application-name: "Spear"
    component: "Secrets for environment variables"
type: Opaque
stringData:  
  sumologicUrl: "blah"
  instanceUrl: "blah"
  instanceApiKey: "blah"
  environment: "Development"
  openFeatureClientId: "blah"
